services:
  front:
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
      - "3333:3333"
    networks:
        db_network:
    depends_on:
       - db

  db:
    image: postgres:14.2
    env_file: .env
    volumes:
      - "postgresql:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
        db_network:                    
            
volumes:
  postgresql:

networks:
  db_network:
